# Admin credentials
SUPERADMIN_PASSWORD = "superadmin123"
DEFAULT_ADMIN_PASSWORD = "admin123"
SENIOR_PASSWORD = "senior123"

# Email settings (optional)
SMTP_SERVER = ""
SMTP_PORT = "587"
SMTP_USERNAME = ""
SMTP_PASSWORD = ""

# Custom directory path (optional override)
SYSTEM_DIR = "system"